# This file will be included by the Makefile under the project directory.

FLOAT_OBJ := $(FLOAT:.a=.o)

$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

$(FLOAT_OBJ): $(LIB_COMMON_DIR)/FLOAT.c
	mkdir -p obj/$(LIB_COMMON_DIR)
	$(CC) -c -o $(FLOAT_OBJ) $(LIB_COMMON_DIR)/FLOAT.c -march=i686 -fno-builtin
